print('Program starting.\n')
Wo1=input('Insert a closed compound word: ')
print("The word you inserted is ",Wo1,sep="'",end="'")
print(" and in reverse it is ",Wo1[::-1],sep="'",end="'.")
print(f'\nThe inserted word length is {len(Wo1)}')
print(f'Last character is ',Wo1[-1:],sep="'",end="'\n")
print('\nTake substring from the inserted word by inserting...')
Num1=int(input('1) Starting point: '))
Num2=int(input('2) Ending point: '))
Num3=int(input('3) Step size: '))
print(f'\nThe word \'{Wo1}\' sliced to the defined substring is \'{Wo1[Num1:Num2:Num3]}\'.\nProgram ending.')